### ISSUE TITLE
Multiple Language Versions

### ISSUE THREAD

**Issue by bbbbbr** [bbbbbr/gb-wordle#1]
### Dictionaries
Right now, for simplicity and to avoid having to change the dictionary compression other languages will use a word list with the non-english A-Z characters filtered out (umlauts, tildes, etc).

### UI Text
In-game messages may also be translated, but it have restrictions too:
* A-Z characters only
* Maximum line width (including any numbers if present) is 18 characters. In some cases it might be ok to use two lines for the translated version, but that will require making the popup dialog box taller. 
* Some examples of the source text:
  * https://github.com/bbbbbr/gb-wordle/blob/main/src/gameplay.c#L56
  * https://github.com/bbbbbr/gb-wordle/blob/main/src/stats.c#L60

**Comment by bbbbbr** [comment]
These are *Solution and Dictionary word lists* only, for review and correction. They are not ROM .gb or .pocket files:

German
[lang_de.zip](https://github.com/bbbbbr/gb-wordle/files/8192282/lang_de.zip)

Spanish
[lang_es.zip](https://github.com/bbbbbr/gb-wordle/files/8192288/lang_es.zip)

French
[lang_fr.zip](https://github.com/bbbbbr/gb-wordle/files/8192289/lang_fr.zip)

Italian
[lang_it.zip](https://github.com/bbbbbr/gb-wordle/files/8192290/lang_it.zip)

**Comment by bbbbbr** [comment]
Test build for German language
* All words with non-English `A-Z` characters are removed from the answer and dictionary lists. 
[GBWORDYL_0.75_de.gb.zip](https://github.com/bbbbbr/gb-wordle/files/8194849/GBWORDYL_0.75_de.gb.zip)

**Comment by lordelan** [comment]
Thank you very much @bbbbbr 
Would you mind adding a *.pocket file too though?

**Comment by bbbbbr** [comment]
**New test builds, more languages**
- Adds a popup-dialog at the start indicating which language (using 2-letter code)
- For non-english it adds a notice:   "A..Z  only, no special chars"
- Added the .pocket builds

**Please let me know if there are:**
 - Problems with the game itself
 - If the language doesn't match the ROM filename
 - Solution words that are incorrect or offensive and should be removed

**Game UI Text**
  - The game UI text is not yet translated, but if anyone wants to try for a given language then see the requirements in this comment above: https://github.com/bbbbbr/gb-wordle/issues/1#issue-1160564605

[GBWORDYL_0.76_GB-and-Pocket_DE_EN_ES_FR_IT_NL.zip](https://github.com/bbbbbr/gb-wordle/files/8222385/GBWORDYL_0.76_GB-and-Pocket_DE_EN_ES_FR_IT_NL.zip)

**Comment by bbbbbr** [comment]
And **Latin** - seems like a cool idea :stuck_out_tongue_winking_eye: 

The method for accumulating the Latin dictionary and answer list was extremely haphazard, so they may be unreliable and have inaccuracies. I also don't know Latin, so will try to find some help reviewing it.

[GBWORDYL_0.76_2_GB-and-Pocket__Latin.zip](https://github.com/bbbbbr/gb-wordle/files/8228354/GBWORDYL_0.76_2_GB-and-Pocket__Latin.zip)

**Comment by bbbbbr** [comment]
New build:
* Fixes an issue where the solution word was blank sometimes
* Now almost all printed text should be translatable (with English A-Z chars)
* German version has most UI text translated (credit: skite2001 + some google translate. I mangled some to fit it)

**Default UI Language Strings:**
https://github.com/bbbbbr/gb-wordle/blob/feature/multilang/src/lang_text_defaults.inc

**Example of how to override them (German):**
https://github.com/bbbbbr/gb-wordle/blob/feature/multilang/src/lang_de/lang_text.h

[GBWORDYL_0.77_GB-and-Pocket_DE_EN_ES_FR_IT_NL.zip](https://github.com/bbbbbr/gb-wordle/files/8237348/GBWORDYL_0.77_GB-and-Pocket_DE_EN_ES_FR_IT_NL.zip)

**Comment by bbbbbr** [comment]
DE Lang Build with translation fixes by skite2001 @ f40132b2e8d4a40f9f91eab1586d073e41a2642a

**Comment by bbbbbr** [comment]
Fix stats popup bug @ 7c11aed3c27138a5bacc68967f99654cc2af9c38
[GBWORDYL_0.77.2_GB-and-Pocket_DE.zip](https://github.com/bbbbbr/gb-wordle/files/8238648/GBWORDYL_0.77.2_GB-and-Pocket_DE.zip)

**Comment by bbbbbr** [comment]
New build is posted in this thread (feel free to join the discussion there if you want):
https://github.com/bbbbbr/gb-wordle/issues/2

A bunch more text strings have been added which may benefit from translation in the German version.
https://github.com/bbbbbr/gb-wordle/blame/develop/src/lang_de/lang_text.h

Note: 16 is the max setting for dialog height, it's full screen (ex: `DIALOG_TEXT_HEIGHT_LINES(16)`)

**Comment by bbbbbr** [comment]
New build with updated German translations from skite2001 here:
https://github.com/bbbbbr/gb-wordle/issues/2#issuecomment-1074567749

**Comment by bbbbbr** [comment]
New version (0.85) with multiple language support has been released

**Comment by bbbbbr** [comment]
Updated 0.85 build with Spanish UI text for test
[GBWORDYL_0.85_ES_-_GB_and_Pocket_2022_03_26.zip](https://github.com/bbbbbr/gb-wordle/files/8356620/GBWORDYL_0.85_ES_-_GB_and_Pocket_2022_03_26.zip)

**Comment by bbbbbr** [comment]
Updated Spanish UI build (v2)
[GBWORDYL_0.85_ES_-_GB_and_Pocket_2022_03_26-V2.zip](https://github.com/bbbbbr/gb-wordle/files/8356772/GBWORDYL_0.85_ES_-_GB_and_Pocket_2022_03_26-V2.zip)

**Comment by bbbbbr** [comment]
Updated Spanish UI build (v3)
[GBWORDYL_0.85_ES_-_GB_and_Pocket_2022_03_26-V3.zip](https://github.com/bbbbbr/gb-wordle/files/8358085/GBWORDYL_0.85_ES_-_GB_and_Pocket_2022_03_26-V3.zip)

**Comment by bbbbbr** [comment]
Updated Spanish UI build (v4)
[GBWORDYL_0.85_ES_-_GB_and_Pocket_2022_03_26-V4.zip](https://github.com/bbbbbr/gb-wordle/files/8358158/GBWORDYL_0.85_ES_-_GB_and_Pocket_2022_03_26-V4.zip)

**Comment by bbbbbr** [comment]
Updated Spanish UI build (v5)
[GBWORDYL_0.85_ES_-_GB_and_Pocket_2022_03_26-V5.zip](https://github.com/bbbbbr/gb-wordle/files/8366437/GBWORDYL_0.85_ES_-_GB_and_Pocket_2022_03_26-V5.zip)

**Comment by bbbbbr** [comment]
For review:

The existing limitation applies: it uses a word list with the non-english A-Z characters filtered out (umlauts, tildes, etc).

- PT-BR (v1): [GBWORDYL_0.85.2_PT-BR.zip](https://github.com/bbbbbr/gb-wordle/files/8415070/GBWORDYL_0.85.2_PT-BR.zip)

- If you don't mind, could you look through the "solution list" (it is not the full dictionary) to see if there any offensive or non-family-friendly words which should not be included? : https://github.com/bbbbbr/gb-wordle/blob/develop/compress/answers_pt-br.txt

- If you think it is suitable to just strip the accent marks from characters (`único` -> `unico`) then it may be possible to increase the dictionary by a couple thousand words and make it more complete.
