### ISSUE TITLE
Missing valid word

### ISSUE THREAD

**Issue by copperkiddx** [bbbbbr/gb-wordle#3]
The word SLAVE is missing from the dictionary

**Comment by bbbbbr** [comment]
It seems when NYT bought it they purged some words from both the solution list and the dictionary. This version mostly tracks those. I'm sympathetic to the solution list changes, less so to the dictionary ones.

https://boingboing.net/2022/02/11/pussy-pupal-and-agora-among-words-removed-from-wordle-after-move-to-new-york-times.html

What's interesting is there are several other family friendly words they didn't remove from the solution list : 
e7691c41dc126bd3e4cfe95af1ff64636cc58efb

I can look into a more detailed list of what they removed from the dictionary

**Comment by bbbbbr** [comment]
While I don't see press about it, it appears they've restored those words to their dictionary and added a couple more. I'll merge for next release.

**Comment by copperkiddx** [comment]
> While I don't see press about it, it appears they've restored those words to their dictionary and added a couple more. I'll merge for next release.

Thank you! Love your version so much
