### ISSUE TITLE
Daily Challenge

### ISSUE THREAD

**Issue by Kroc** [bbbbbr/gb-wordle#9]
The EverDrive-GB X7 has a Real-Time-Clock, so a true daily challenge could be supported.
(I know you're not working on this game now, I'm just putting out there in case anybody else sees it and wants to take it on)

A Solitaire game I play on my phone has a similar daily challenge, and a calendar that allows you to go back to complete previous days should you miss them but does not allow you to skip forward into the future.

![image](https://user-images.githubusercontent.com/142650/175306524-9374e53f-61a7-43a3-8b90-d1df911a1a24.png)

**Comment by bbbbbr** [comment]
No RTC support planned for now. There is probably not code space to support it until the 31K limit is lifted and everything gets banked. The physical cart release targeted a specialty 31k ROM +1k Flash cart, so everything has been built to fit into that.

https://github.com/bbbbbr/gb-wordle/blob/main/romusage.txt
```
Bank           Range             Size   Used   Used%  Free   Free% 
----------     ----------------  -----  -----  -----  -----  -----
ROM            0x0000 -> 0x3FFF  16384  16002    97%    382     2%
ROM_0          0x4000 -> 0x7FFF  16384  16254    99%    130     0%
```

There is another GB Wordle you can try which does have that feature, though it is very bare bones.
https://github.com/SNBeast/WordleBoy/releases/tag/v1.1.0
